stages:
  - test
  - build

job_test:
  stage: test
  image: cypress/included:13.6.3
  script:
    - echo "Running Cypress E2E tests..."
  # artifacts:
  #   when: always
  #   paths:
  #     - cypress/videos/
  #     - cypress/screenshots/
  #   expire_in: 1 week


job_build:
  stage: build
  image: node:18
  script:
    - echo "running build.... "
    - npm ci
    - npm run build
