stages:
  - test
  - build

job_test:
  stage: test
  image: cypress/browsers:node-22.16.0-chrome-137.0.7151.68-1-ff-139.0.1-edge-137.0.3296.62-1
  before_script:
    - cd luxuryproducts_frontend
    - npm ci
    - npx cypress install
    - npm install --save-dev wait-on
  script:
    - echo "Starting Angular app..."
    - npx ng serve --host 0.0.0.0 &
    - npx wait-on http://localhost:4200
    - echo "Running Cypress tests in Chrome..."
    - npx cypress run --browser chrome --config baseUrl=http://localhost:4200


job_build:
  stage: build
  image: node:18
  script:
    - echo "Building Angular app..."
    - npm ci
    - npm run build
